# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tsr_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsr',
            name='percent_contribution',
            field=models.IntegerField(default=0),
        ),
    ]
