# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20171018_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsr',
            name='percent_contribution',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
